"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var chalk = require("chalk");
exports.info = console.log.bind(console, ' [suman-r] ');
exports.error = console.log.bind(console, chalk.red.bold(' [suman-r] '));
exports.warning = console.log.bind(console, chalk.yellow.bold(' [suman-r] '));
exports.good = console.log.bind(console, chalk.cyan.bold(' [suman-r] '));
exports.veryGood = console.log.bind(console, chalk.green.bold(' [suman-r] '));
var $exports = module.exports;
exports.default = $exports;
